### ISSUE TITLE
Thought/suggestion/observation: simple if else

### ISSUE THREAD

**Issue by rpkarlsson** [mw222rs/1DV450_mw222rs#1]
https://github.com/mw222rs/1DV450_mw222rs/blob/master/app/controllers/api_keys_controller.rb#L8

Don't really know if you've seen this or if it is a conscious choice because you prefer it this way. Just thought i'd show you anyway.

``` ruby
@api_keys = if current_user.admin?
              ApiKey.all
            else
              current_user.api_keys
            end
```

can be done as:

``` ruby
@api_keys = current_user.admin? ? ApiKey.all : current_user.api_keys
```

As to if its better or not I leave up to you.

**Comment by fyrkant** [comment]
Oneliners are a beautiful thing, thanks!
