### ISSUE TITLE
Consider separation of concerns with namespaced controllers

### ISSUE THREAD

**Issue by rpkarlsson** [mw222rs/1DV450_mw222rs#2]
One improvement could be to split the normal users api_key logic and the admins api_key logic with
namespaces.

``` shell
$ rails generate controller admin/api_key
$ rails destroy controller admin/api_key
```

Should enable you to easily see an example (and clean up afterwards) if you are interested.

See link for some more info on namespaced controllers and routing.

http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing

**Comment by fyrkant** [comment]
A different admin namespace looks like a great solution, definitely looking into it. 

Thank you, and brace yourself for a barrage of questions when I mess up trying to implement this! :wink:

**Comment by 1dv450** [comment]
:+1:

**Comment by fyrkant** [comment]
Oh I should have closed this one back with [this commit](https://github.com/mw222rs/1DV450_mw222rs/commit/42fbaf9db761b7e74882065b4644a55a2abfb5c2)!
