### ISSUE TITLE
List events

### ISSUE THREAD

**Issue by jc222fi** [mw222rs/1DV450_mw222rs#7]
According to the requirements list for the assignment you should sort the list of events based on when it was added, now it is sorted on the date for when the event will take place. Just switch for the timestamp in the events_controller instead of date.

**Comment by fyrkant** [comment]
Hmm, I think this is up for discussion, I interpreted Johns requirements as it was the date of the event and not the created_at timestamp. Anyway, as you say it's easy to change if one would want to in the future. Closing this, thanks!
